config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  root to: 'pages#home'
  resources :contacts, only: [:new, :create]
  resources :artistes do
    resources :nouveautes, except: [:destroy, :edit, :update, :index]
  end

  resources :nouveautes, only: [:destroy, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artiste.rb
class Artiste < ApplicationRecord
  has_many :nouveautes, dependent: :destroy
  has_one_attached :photo
  has_one_attached :reseau1
  has_one_attached :reseau2
  has_one_attached :reseau3
  has_one_attached :reseau4
  has_one_attached :reseau5
  has_one_attached :reseau6
  has_one_attached :photo_redirection_youtube
  validates :name, :genre, :photo, :photo_redirection_youtube, presence: true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form",
      :to => "sebastienbruno122@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/home.rb
class Home < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "sebastienbruno122@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/nouveaute.rb
class Nouveaute < ApplicationRecord
  belongs_to :artiste
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  private

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/artistes_controller.rb
class ArtistesController < ApplicationController

  def index
    @artistes = Artiste.all
  end

  def show
    @artiste = Artiste.find(params[:id])
    @video1 = Conred::Video.new(
      video_url: @artiste.youtube_nouveaute1,
      width: 285,
      height: 185,
      error_message: "Video url is invalid"
    )
    @video2 = Conred::Video.new(
      video_url: @artiste.youtube_nouveaute2,
      width: 285,
      height: 185,
      error_message: "Video url is invalid"
    )
    @video3 = Conred::Video.new(
      video_url: @artiste.youtube_nouveaute3,
      width: 285,
      height: 185,
      error_message: "Video url is invalid"
    )
    @video4 = Conred::Video.new(
      video_url: @artiste.youtube_nouveaute4,
      width: 285,
      height: 185,
      error_message: "Video url is invalid"
    )
  end

  def new
    @artiste = Artiste.new
  end

  def create
    @artiste = Artiste.new(artiste_params)
    if @artiste.save
      redirect_to artiste_path(@artiste.id)
    else
      render :new
    end
  end

  def edit
    @artiste = Artiste.find(params[:id])
  end

  def update
    @artiste = Artiste.find(params[:id])
    @artiste.update(artiste_params)
    redirect_to artiste_path(@artiste)
  end

  def destroy
    @artiste = Artiste.find(params[:id])
    @artiste.destroy
    redirect_to artistes_path
  end

  private

  def artiste_params
    params.require(:artiste).permit(:name, :genre, :biography, :photo, :youtube_link, :description, :les_dessous, :youtube_nouveaute1, :youtube_nouveaute2, :youtube_nouveaute3, :youtube_nouveaute4, :reseau1, :reseau2, :reseau3, :reseau4, :reseau5, :reseau6, :instagram_link, :spotify_link, :photo_redirection_youtube)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
    # redirect_to contacts_path
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now = 'Merci'
    else
      flash.now[:error] = 'Message ne peut pas être envoyé.'
      render :new
    end
  end
end

app/controllers/nouveautes_controller.rb
class NouveautesController < ApplicationController

  def index
    @nouveautes = Nouveaute.all
  end

  def show
    @nouveaute = Nouveaute.find(params[:id])
  end

  def new
    @artiste = Artiste.find(params[:artiste_id])
    @nouveaute = Nouveaute.new
  end

  def edit
    @nouveaute = Nouveaute.find(params[:id])
  end

  def update
    # @artiste = Artiste.find(params[:artiste_id])
    @nouveaute = Nouveaute.find(params[:id])
    @nouveaute.update(nouveaute_params)
    redirect_to artiste_path(@nouveaute.artiste)
  end

  def create
    @nouveaute = Nouveaute.new(nouveaute_params)
    @artiste = Artiste.find(params[:artiste_id])
    @nouveaute.artiste = @artiste
    @nouveaute.save
    redirect_to artiste_path(@artiste)
  end

    #DELETE /artistes/:id

  def destroy
    @nouveaute = Nouveaute.find(params[:id])
    @nouveaute.destroy
    redirect_to artiste_path(@nouveaute.artiste)
  end

    private

  def nouveaute_params
    params.require(:nouveaute).permit(:citation)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!, only: :home
  def home
    @artistes = Artiste.all
    @nouveautes = Nouveaute.all
  end
  
  def show
    @artiste = Artiste.find(params[:id])
  end
      private

def artiste_params
    params.require(:artiste).permit(:name, :genre, :biography, :photo, :youtube_link, :description, :les_dessous, :youtube_nouveaute1, :youtube_nouveaute2, :youtube_nouveaute3, :youtube_nouveaute4)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artistes_helper.rb
module ArtistesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nouveautes_helper.rb
module NouveautesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/artistes/_artistes_carousel.html.erb
<div class="row block-artist">
    <div class="col-12 col-lg-3 head-block-artist">
      <h3 class="horizontal-header-artiste">Artistes</h3>
      <p class="horizontal-subtitle-artiste">DE TOUT HORIZON</p>
      <p class="line-5"></p>
    </div>
    <div class="col-12 col-lg-9">
    <div class="carousel-body">
      <input type="radio" name="position" checked />
      <input type="radio" name="position" />
      <input type="radio" name="position" />
      <input type="radio" name="position" />
      <input type="radio" name="position" />
      <main id="carousel">
      <% @artistes.each do |artiste| %>
        <div class="item">
          <div class="artiste_home">
        <% if artiste.photo.attached? %>
            <%= cl_image_tag artiste.photo.key, height: 300, width: 300, crop: :fill %>
        <%= link_to artiste_path(artiste), class: "text-decoration-none" do %>
        <% end %>
        <% end %>
          </div>
        <h2> <%= artiste.name %></h2>
        <h4> <%= artiste.genre %></h4>
        </div>
      <% end %>
        <main>
    </div>

    </div>

</div>

app/views/artistes/_artistes_list.html.erb
<div class="container">
  <div>
  <% if user_signed_in? %>
  <%= link_to "Add new artiste", new_artiste_path %>
  <% end %>
  </div>
  <div class="cards-index">
      <% @artistes.each do |artiste| %>
        <%= link_to artiste_path(artiste), class: "text-decoration-none" do %>
        <div class="card-trip">
          <div class="card-info">
           <h2> <%= artiste.name %></h2>
           <h4> <%= artiste.genre %></h4>
          </div>
            <% if artiste.photo.attached? %>
            <%= cl_image_tag artiste.photo.key, height: 300, width: 300, crop: :fill %>
            <% end %>
            <% if user_signed_in? %>
              <%= link_to "delete", artiste_path(artiste), method: :delete %>
            <% end %>
              <% end %>
         </div>
      <% end %>
  </div>
</div>

app/views/artistes/_iphones.html.erb
        <div class="iphonetest">
          <% if @artiste.reseau1.attached? %> 
            <div class="iphone1">
              <div class="title_logo">
                <p class="ecriture_insta">INSTAGRAM</p>
                <%= link_to @artiste.instagram_link, target: "_blank", class:"redirection_reseaux_insta" do%>
                  <i class="fab fa-instagram fa-2x" id="instagram" ></i>
                <% end %>
              </div>
              <div class="iphone_structure">
                    <%= cl_image_tag @artiste.reseau1.key, crop: :fill, :class => 'img-s-reseau1' %>
              </div>
            </div>
          <% end %>
          <% if @artiste.reseau2.attached? %> 
            <div class="iphone1">
              <div class="title_logo">
                <p class="ecriture_spotify">SPOTIFY</p>
                <%= link_to @artiste.spotify_link, target: "_blank",class:"redirection_reseaux_spotify" do%>
                  <i class="fab fa-spotify fa-2x" id="spotify"></i>
                <% end %>
              </div>
              <div class="iphone_structure">
                <%= cl_image_tag @artiste.reseau2.key, crop: :fill, :class => 'img-s-reseau2' %>
              </div>
            </div>
          <% end %>
          <% if @artiste.reseau3.attached? %> 
            <div class="iphone1">
              <div class="title_logo">
                <p class="ecriture_youtube">YOUTUBE</p>
                <%= link_to @artiste.youtube_link_for_contacts, target: "_blank", class:"redirection_reseaux_youtube" do%>
                  <i class="fab fa-youtube fa-2x" id="youtube" ></i>
                <% end %>
              </div>
              <div class="iphone_structure">
                <%= cl_image_tag @artiste.reseau3.key, crop: :fill, :class => 'img-s-reseau3' %>
              </div>
            </div>
          <% end %>
          <% if @artiste.reseau4.attached? %> 
            <div class="iphone1">
              <div class="title_logo">
                <p class="ecriture_tiktok">TIKTOK</p>
                <%= link_to @artiste.tiktok_link,target: "_blank", class:"redirection_reseaux_tiktok" do%>
                  <i class="fab fa-tiktok fa-2x", id="tiktok" ></i>
                <% end %>
              </div>
              <div class="iphone_structure">
                <%= cl_image_tag @artiste.reseau4.key, crop: :fill, :class => 'img-s-reseau4' %>
              </div>
            </div>
          <% end %>
          <% if @artiste.reseau5.attached? %> 
            <div class="iphone1">
              <div class="title_logo">
                <p class="ecriture_vimeo">VIMEO</p>
                <%= link_to @artiste.vimeo_link,target: "_blank", class:"redirection_reseaux_vimeo" do%>
                  <i class="fab fa-vimeo fa-2x", id="vimeo" ></i>
                <% end %>
              </div>
              <div class="iphone_structure">
                <%= cl_image_tag @artiste.reseau5.key, crop: :fill, :class => 'img-s-reseau4' %>
              </div>
            </div>
          <% end %>
          <% if @artiste.reseau6.attached? %> 
            <div class="iphone1">
              <div class="title_logo">
                <p class="ecriture_facebook">FACEBOOK</p>
                <%= link_to @artiste.facebook_link,target: "_blank",class:"redirection_reseaux_facebook" do%>
                  <i class="fab fa-facebook fa-2x", id="facebook" ></i>
                <% end %>
              </div>
              <div class="iphone_structure">
                <%= cl_image_tag @artiste.reseau6.key, crop: :fill, :class => 'img-s-reseau4' %>
              </div>
            </div>
          <% end %>
        </div>

app/views/artistes/_youtube.html.erb
      <div class="cards">
        <% unless @artiste.youtube_nouveaute1.empty? %>
          <%= @video1.code.html_safe %>
        <% end %>
        <% unless @artiste.youtube_nouveaute2.empty? %>
          <%= @video2.code.html_safe %>
        <% end %>
        <% unless @artiste.youtube_nouveaute3.empty? %>
          <%= @video3.code.html_safe %>
        <% end %>
        <% unless @artiste.youtube_nouveaute4.empty? %>
          <%= @video4.code.html_safe %>
        <% end %>
      </div>

app/views/artistes/edit.html.erb
<h1> edit</h1>


<div class="container">
  <div class="row edit">
    <div class="col-6 offset-3">
      <%= simple_form_for @artiste do |f| %>
        <%= f.input :name %>
        <%= f.input :genre %>
        <%= f.input :biography %>
        <%= f.input :description %>
        <%= f.input :les_dessous %>
        <%= f.input :youtube_link %>
        <%= f.input :youtube_nouveaute1, label: 'Vidéo youtube 1: section videos' %>
        <%= f.input :youtube_nouveaute2, label: 'Vidéo youtube 2: section videos' %>
        <%= f.input :youtube_nouveaute3, label: 'Vidéo youtube 3: section videos' %>
        <%= f.input :youtube_nouveaute4, label: 'Vidéo youtube 4: section videos' %>
        <%= f.input :instagram_link, label: 'Lien instagram pour contacts'%>
        <%= f.input :spotify_link, label: 'Lien spotify pour contacts'%>
        <%= f.input :tiktok_link, label: 'Lien tiktok pour contacts'%>
        <%= f.input :youtube_link_for_contacts, label: 'Lien youtube pour contacts'%>
        <%= f.input :vimeo_link, label: 'Lien vimeo pour contacts'%>
        <%= f.input :facebook_link, label: 'Lien facebook pour contacts'%>
        <%= f.input :photo, as: :file, label: 'Photo Artiste - Dimention : 630px : 420px' %>
        <%= f.input :photo_redirection_youtube, as: :file, label: 'Photo redirection youtube - Dimention : 176px : 161px' %>
        <%= f.input :reseau1, as: :file, label: 'screenshot insta - Dimention : 237px : 420px'%>
        <%= f.input :reseau2, as: :file, label: 'screenshot spotify - Dimention : 237px : 420px'%>
        <%= f.input :reseau3, as: :file, label: 'screenshot youtube - Dimention : 237px : 420px'%>
        <%= f.input :reseau4, as: :file, label: 'screenshot tiktok - Dimention : 237px : 420px'%>
        <%= f.input :reseau5, as: :file, label: 'screenshot vimeo - Dimention : 237px : 420px'%>
         <%= f.input :reseau6, as: :file, label: 'screenshot facebook - Dimention : 237px : 420px'%>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/artistes/index.html.erb
<div class="container">

<h1><strong>Les artistes</strong></h1>
  <div class="artistes_index">>
  <% if user_signed_in? %>
  <%= link_to "Add new artiste", new_artiste_path %>
  <% end %>
  </div>
  <div class="cards-index">
      <% @artistes.each do |artiste| %>
        <%= link_to artiste_path(artiste), class: "text-decoration-none" do %>
        <div class="card-trip mb-3">
          <div class="card-info p-2">
           <h2> <%= artiste.name %></h2>
           <h4> <%= artiste.genre %></h4>
          </div>
            <% if artiste.photo.attached? %>
            <%= cl_image_tag artiste.photo.key, height: 300, width: 300, crop: :fill %>
            <% end %>
            <% if user_signed_in? %>
              <%= link_to "delete", artiste_path(artiste), method: :delete %>
              <% end %>
              <% end %>
         </div>
      <% end %>
  </div>
</div>

app/views/artistes/show.html.erb
<div class="container">
  <div class="row top">

    <div class="col-12 col-lg-8 artiste_block_1">
      <div class="artiste_name_genre">
        <h1 class="main-header-show"><%= @artiste.name %></h1>
        <p class="artiste-genre"><%= @artiste.genre %></p>
      </div>
          <p class="line-1-show"></p>
          <p class="line-2-show"></p>
        <p class="artiste-description"><%= @artiste.description %></p>
    </div>

    <div class="col-12 col-lg-4">
        <% if @artiste.photo.attached? %>
        <div>
          <%= cl_image_tag @artiste.photo.key, crop: :fill, :class => 'img-s-artiste' %>
          <div class="card-s-youtube">
            <% if @artiste.photo_redirection_youtube.attached? %> 
              <%= cl_image_tag @artiste.photo_redirection_youtube.key, crop: :fill %>
            <% end %>
            <div class="card-s-youtube-name">
                <h2>
                <%= @artiste.name %>
                <a href="<%= @artiste.youtube_link %>" target="_blank"> <i class="fas fa-play-circle"></i></a>
                </h2>
            </div>
          </div>
        </div>
        <% end %>
        <% if user_signed_in? %>
         <%= link_to "edit", edit_artiste_path , class: 'btn btn-primary'%>
        <% end %>
         <% if user_signed_in? %>
          <%= link_to "Add new nouveautés", new_artiste_nouveaute_path(@artiste) %>
          <% end %>
    </div>

  </div>
</div>


<div id="show-container" class="container mt-5 ">

  <div class="biography">
    <div class="col-12 col-lg-3">
      <h3 class="bio-s-title">BIOGRAPHY</h3>
      <p class="line-3-show"></p>
      <%# <p class="line-3-show-bis"></p> %>
    </div>
    <div class="col-12 col-lg-9">
      <p class="bio-s"><%= @artiste.biography %></p>
    </div>
  </div>

<% if @artiste.les_dessous != "" %> 
  <div class="dessous">
    <div class="col-12 col-lg-3">
      <p class="dessous-s-title">LES DESSOUS DE L’ENTREVUE</p>
      <p class="line-4-show"></p>
      <%# <p class="line-4-show-bis"></p> %>
    </div>

    <div class="col-12 col-lg-9">
        <p class="dessous-s"> <%= @artiste.les_dessous %></p>
    </div>
  </div>
<% end %>

<% if (@artiste.youtube_nouveaute1 || @artiste.youtube_nouveaute2 || @artiste.youtube_nouveaute3 || @artiste.youtube_nouveaute4) != "" %> 
  <div class="dernieres">
    <div class="col-12 col-lg-3">
      <p class="dessous-s-title">DERNIÈRES SORTIES</p>
      <p class="line-5-show"></p>
      <%# <p class="line-5-show-bis" id="lignes_dernieres"></p> %>
    </div>

    <div class="col-12 col-lg-9">
      <%= render partial: 'artistes/youtube', locals: {artiste: @partiste, youtube_nouveaute1: @youtube_nouveaute1, user: @user} %>
    </div>
  </div>
<% end %>

    <div class="contact">

      <div class="col-12 col-lg-3">
        <p class="dessous-s-title">CONTACT</p>
        <p class="line-6-show"></p>
        <%# <p class="line-6-show-bis"></p> %>
      </div>

      <div class="col-12 col-lg-9">
        <%= render partial: 'artistes/iphones' %>
      </div>
    </div>
</div>

<div>
  <%= link_to "back to list", artistes_path, class: 'btn btn-light' %>
</div>
</div>

app/views/contacts/_create.html.erb
<h1>Thank you for leaving us a message</h1>

app/views/contacts/_new.html.erb
<h1 class="main-header-6" id="contact">Discutons !</h1>
<div class="form-block">
  <div class="row">
    <div class="col-12 col-lg-3 block-contact">
      <h3 class="horizontal-header-contact">CONTACT</h3>
      <p class="horizontal-subtitle-contact">ENVOIE DE L’AMOUR</p>
      <p class="line-contact"></p>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-lg-9">
      <%= form_for :contact , :html => {:class => "form-horizontal", :role => "form"}, url: contacts_path, remote: true do |f|%>
          <div class="col-md-6 position-form">
              <%= f.label :name %>

              </br>

                <%= f.text_field  :name, required: true, class: "contact-form-text-area", placeholder: "TON NOM OU PSEUDONYME" %></br>

              <%= f.label :email %>

              </br>

              <%= f.text_field :email, required: true, class: "contact-form-text-area", placeholder: "TON EMAIL" %></br>

              </br>

               <label for="exampleFormControlSelect1">choisi un sujet</label>
                <select class="contact-form-text-area" id="exampleFormControlSelect1">
                  <option>Je suis interessé pour une entrevue</option>
                  <option>Offre de partenariat</option>
                </select>


            <%= f.label :message %>
              </br>

            <%= f.text_area :message, as: :text, rows: 8, cols: 40, required: true, class: "contact-form-text-area",
                              placeholder: "DIS NOUS EN PLUS!"%></br>

            <div class= "hidden">
              <%= f.label :nickname %>
              <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
            </div>

            <%= f.submit 'Envoyer', class: 'btn btn-light' %>
          </div>
        <% end %>
        <div class="col-md-6" id="flash-message">
          <%= render 'home/flash' %>
        </div>
    </div>
  </div>
</div>

app/views/contacts/create.html.erb
<h1>Thank you for leaving us a message</h1>

app/views/home/_contact_form.html.erb
<div class="row form-block">
  <h1 class="main-header-6" id="contact">Discutons !</h1>
  <div class="col-12 col-lg-3">
    <h3 class="horizontal-header-contact">CONTACT</h3>
    <p class="horizontal-subtitle-contact">ENVOIE DE L’AMOUR</p>
    <p class="line-contact"></p>
  </div>
  <div class="col-12 col-lg-9">
    <%= form_for :contact , :html => {:class => "form-horizontal", :role => "form"}, url: home_index_path, remote: true do |f| %>
        <div class="col-md-6 form-position">
            <%= f.label :name %></br>
              <%= f.text_field  :name, required: true, class: "contact-form-text-area", placeholder: "TON NOM OU PSEUDONYME" %></br>

            <%= f.label :email %></br>
            <%= f.text_field :email, required: true, class: "contact-form-text-area", placeholder: "TON EMAIL" %></br>

          <%= f.label :message %></br>
          <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area",
                            placeholder: "DIS NOUS EN PLUS!"%></br>

          <div class= "hidden">
            <%= f.label :nickname %>
            <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
          </div>

          <%= f.submit 'Envoyer', class: 'btn btn-light' %>
        </div>
      <% end %>
      <div class="col-md-6" id="flash-message">
        <%= render 'home/flash' %>
      </div>
  </div>
</div>

app/views/nouveautes/_carousel_nouveautes.html.erb
  <div class="container carousel-position">
    <div id="product-carousel" class="carousel-border carousel slide py-3" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
    <div class="carousel-inner">
      <% @nouveautes.each_with_index do |nouveaute, i| %>
        <div class="carousel-item <%= "active" if i == 0 %>">
          <div class="a_index">
            <div class="artiste_index"> <%=  nouveaute.artiste.name%> </div>
            <div class="genre_index"> <%=  nouveaute.artiste.genre%> </div>
          <% if user_signed_in? %>
            <div class="citations_index"> <%=  nouveaute.citation%> 
         <%= link_to "edit", edit_nouveaute_path([nouveaute.id]) , class: 'btn-nouveautes'%>
        <% end %></div>
          </div>
            <%= cl_image_tag nouveaute.artiste.photo_redirection_youtube.key, height: 400, class: "d-block rounded" %>
        </div>
      <% end %>
     </div>
        <a class="carousel-control-prev" href="#product-carousel" role="button" data-slide="prev" style="bottom:-157px;">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#product-carousel" role="button" data-slide="next" style="bottom:-157px;">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

app/views/nouveautes/_citations.html.erb
<div>
    <h5> Citations</h5>
        <% nouveautes.each do |nouveaute| %>
        <li class="list-group-item"><%= nouveaute.citation %> id: <%= nouveaute.id %> 
            <% if user_signed_in? %>
                <%= link_to "Supprimer", nouveaute_path(nouveaute), method: :delete, class: 'btn btn-danger' %> 
                <%= link_to "edit", edit_nouveaute_path(nouveaute), class: 'btn btn-light' %></li>
                <%= link_to "create citation", new_artiste_nouveaute_path(@artiste), class: 'btn btn-primary' %>
            <% end %>
        <% end %>
<div>

app/views/nouveautes/new.html.erb
<div class="container nouveautes_new">
  <div class="row">
    <div class="col-6 offset-3">
        <%= simple_form_for([@artiste, @nouveaute]) do |f| %>
          <%= f.input :citation %>
          <%= f.submit "create" %>
        <% end %>
   </div>
  </div>
</div>
  <%= link_to "Retour", artiste_nouveautes_path(), class: 'btn btn-light' %>

app/views/nouveautes/show.html.erb
<h1>this is nouveaute show</h1>

<div>
  <p><%= @nouveaute.citation %></p>
</div>

<div>
  <%# <%= link_to "edit", nouveaute_path, class: "btn btn-warning" %> %>
</div>
<div>
  <%= link_to "Supprimer", nouveaute_path, method: :delete, class: 'btn btn-danger' %>
</div>
<div>
  <%= link_to "back to list", artiste_nouveautes_path, class: "btn btn-primary" %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-block">
  <div class="navbar transparent navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to root_path, class: "logo-navbar" do %>
        <%= cl_image_tag("xygap41xkfo0pgvps4ri", class: "logo-navbar")%>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse pr-5" id="navbarSupportedContent">
        <ul class="navbar-nav pr-5 mr-auto">
          <li class="nav-item active">
          <strong><%= link_to "Ce que l'on fait", root_path(anchor: 'wwd'), class: "nav-link nav-title text-dark" %></strong>
          </li>
          <li class="nav-item">
            <strong><%= link_to "Nouveautés", nouveautes_path, class: "nav-link nav-title text-dark" %></strong>
          </li>
          <li class="nav-item">
            <strong><%= link_to "Les artistes", root_path(anchor: 'artistes'), class: "nav-link nav-title text-dark" %></strong>
          </li>
          <li class="nav-item">
            <strong><%= link_to "À propos", root_path(anchor: 'about'), class: "nav-link nav-title text-dark" %></strong>
          </li>
          <li class="nav-item">
            <strong><%= link_to "Contact", root_path(anchor: 'contact'), class: "nav-link nav-title text-dark" %></strong>
          </li>
          </li>
        </ul>
      </div>
  </div>
</div>